import { Column, ColumnTypeEnum } from '../table';

export class LegalRequestTable {
  public static legalRequestColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'legalRequestID',
      canSort: false,
      type: ColumnTypeEnum.Radio,
      sortByServer: true,
    },
    {
      displayName: 'סוג בקשה',
      propertyName: 'requestTypeID',
      sortField: 'type',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
      hasIcon: true,
      fieldId: 'requestTypeID',
    },
    {
      displayName: 'סטטוס',
      propertyName: 'status',
      canSort: true,
      type: ColumnTypeEnum.Tag,
      sortByServer: true,
      fieldId: 'statusID',
    },
    {
      displayName: 'מספר זהות',
      propertyName: 'nid',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'firstName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
      additionalText: 'lastName',
    },
    {
      displayName: 'מספר רישוי',
      propertyName: 'vehicleNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'מספר דוח',
      propertyName: 'ticketNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'תאריך קליטה',
      propertyName: 'creationDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'אופן ההגשה',
      propertyName: 'requestSource',
      sortField: 'source',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
  ];
  public static MainColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'legalRequestID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: 'סוג בקשה',
      propertyName: 'requestTypeID',
      sortField: 'type',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      hasIcon: true,
      fieldId: 'requestTypeID',
    },
    {
      displayName: 'סטטוס',
      propertyName: 'status',
      canSort: true,
      type: ColumnTypeEnum.Tag,
      sortByServer: false,
      fieldId: 'statusID',
    },
    {
      displayName: 'מספר זהות',
      propertyName: 'nid',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'firstName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      additionalText: 'lastName',
    },
    {
      displayName: 'מספר רישוי',
      propertyName: 'vehicleNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'מספר דוח',
      propertyName: 'ticketNumber',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'תאריך קליטה',
      propertyName: 'creationDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'אופן ההגשה',
      propertyName: 'requestSource',
      sortField: 'source',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
  ];
}
