export enum RequestStatusId {
  RECEIVED = 1,
  APPROVED_BY_CLERK,
  REJECTED_BY_CLERK,
  APPROVED_BY_PROSECUTOR,
  REJECTED_BY_PROSECUTOR,
  DOCUMENTS_COMPLITION,
  TRANSFERRED_TO_BACKOFFICE_CONSULTATION,
  RETURNED_FROM_BACKOFFICE_CONSULTATION,
  TRANSFERRED_TO_PROSECUTOR_CONSULTATION,
  RETURNED_FROM_PROSECUTOR_CONSULTATION,
  AWAITING_JUDGMENT,
  COURT_DECISION
}

export const ClosedStatuses = [
  RequestStatusId.APPROVED_BY_CLERK,
  RequestStatusId.REJECTED_BY_CLERK,
  RequestStatusId.APPROVED_BY_PROSECUTOR,
  RequestStatusId.REJECTED_BY_PROSECUTOR,
];

