import { Column, ColumnTypeEnum } from '../table';

export class TicketTable {
  public MainColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'ticketID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: '',
      propertyName: 'ticketStatusID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: 'סטטוס',
      propertyName: 'ticketStatusName',
      canSort: true,
      type: ColumnTypeEnum.Tag,
      sortByServer: false,
      fieldId: 'ticketStatusID',
    },
    {
      displayName: 'עירייה',
      propertyName: 'authorityName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'זהות/ח.פ',
      propertyName: 'nid',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'name',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      textOverflow: true,
    },
    {
      displayName: 'תאריך עבירה',
      propertyName: 'violationDate',
      canSort: true,
      type: ColumnTypeEnum.Date,
      sortByServer: false,
    },
    {
      displayName: 'מספר דוח',
      propertyName: 'ticketNumber',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'סוג דוח',
      propertyName: 'ticketTypeName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'שלב',
      propertyName: 'ticketStageName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      fieldId: 'ticketStageID',
      hasIcon: true,
    },
    {
      displayName: 'יתרה',
      propertyName: 'paymentBalance',
      canSort: true,
      type: ColumnTypeEnum.Currency,
      sortByServer: false,
    },
    {
      displayName: 'דוחות נוספים',
      propertyName: 'additionalTicketPaymentBalance',
      canSort: false,
      type: ColumnTypeEnum.Currency,
      sortByServer: false,
    },
    {
      displayName: '',
      propertyName: 'ticketStageID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
  ];

  public BackOfficeColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'ticketID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: '',
      propertyName: 'ticketStatusID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: 'סטטוס',
      propertyName: 'ticketStatusName',
      canSort: true,
      type: ColumnTypeEnum.Tag,
      sortByServer: false,
      fieldId: 'ticketStatusID',
    },
    {
      displayName: 'רשות',
      propertyName: 'authorityName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'זהות/ח.פ',
      propertyName: 'nid',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'name',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      textOverflow: true,
    },
    {
      displayName: 'תאריך עבירה',
      propertyName: 'violationDate',
      canSort: true,
      type: ColumnTypeEnum.Date,
      sortByServer: false,
    },
    {
      displayName: 'מספר דוח',
      propertyName: 'ticketNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'סוג דוח',
      propertyName: 'ticketTypeName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'שלב',
      propertyName: 'ticketStageName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      fieldId: 'ticketStageID',
      hasIcon: true,
    },
    {
      displayName: 'יתרה',
      propertyName: 'paymentBalance',
      canSort: true,
      type: ColumnTypeEnum.Currency,
      sortByServer: false,
    },
    {
      displayName: 'דוחות נוספים',
      propertyName: 'additionalTicketPaymentBalance',
      canSort: false,
      type: ColumnTypeEnum.Currency,
      sortByServer: false,
    },
    {
      displayName: '',
      propertyName: 'ticketStageID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
  ];
  public ResultsDropdownColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'ticketID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: '',
      propertyName: 'ticketStatusID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: 'סטטוס',
      propertyName: 'ticketStatusName',
      canSort: false,
      type: ColumnTypeEnum.Tag,
      sortByServer: false,
      hasIcon: true,
      fieldId: 'ticketStatusID',
    },
    {
      displayName: 'עירייה',
      propertyName: 'authorityName',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'זהות/ח.פ',
      propertyName: 'nid',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'name',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      textOverflow: true,
    },
    {
      displayName: 'תאריך עבירה',
      propertyName: 'violationDate',
      canSort: false,
      type: ColumnTypeEnum.Date,
      sortByServer: true,
    },
    {
      displayName: 'מספר דוח',
      propertyName: 'ticketNumber',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'סוג דוח',
      propertyName: 'ticketTypeName',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'שלב',
      propertyName: 'ticketStageName',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      fieldId: 'ticketStageID',
      hasIcon: true,
    },
    {
      displayName: 'יתרה',
      propertyName: 'paymentBalance',
      canSort: false,
      type: ColumnTypeEnum.Currency,
      sortByServer: false,
    },
    {
      displayName: 'דוחות נוספים',
      propertyName: 'additionalTicketPaymentBalance',
      canSort: false,
      type: ColumnTypeEnum.Currency,
      sortByServer: false,
    },
    {
      displayName: '',
      propertyName: 'ticketStageID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
  ];
  public TicketsNewColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'ticketID',
      canSort: false,
      type: ColumnTypeEnum.ActiveStatus,
      sortByServer: true,
    },
    {
      displayName: '',
      propertyName: 'email',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: '',
      propertyName: 'mainPhone',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: '',
      propertyName: 'ticketStatusID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: true,
    },
    {
      displayName: 'סטטוס',
      propertyName: 'ticketStatusName',
      canSort: true,
      type: ColumnTypeEnum.Tag,
      sortByServer: true,
      fieldId: 'ticketStatusID',
    },
    {
      displayName: 'עירייה',
      propertyName: 'authorityName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'מספר זהות',
      propertyName: 'nid',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'name',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
      textOverflow: true,
    },
    {
      displayName: 'תאריך עבירה',
      propertyName: 'violationDate',
      canSort: true,
      type: ColumnTypeEnum.Date,
      sortByServer: true,
    },
    {
      displayName: 'מספר דוח',
      propertyName: 'ticketNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'סוג דוח',
      propertyName: 'ticketTypeName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'שלב',
      propertyName: 'ticketStageName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
      fieldId: 'ticketStageID',
      hasIcon: true,
    },
    {
      displayName: 'יתרה',
      propertyName: 'paymentBalance',
      canSort: true,
      type: ColumnTypeEnum.Currency,
      sortByServer: true,
      textColor: 'blue',
    },
    {
      displayName: 'דוחות נוספים',
      propertyName: 'additionalTicketPaymentBalance',
      canSort: false,
      type: ColumnTypeEnum.Currency,
      sortByServer: true,
      textColor: 'black',
    },
    {
      displayName: '',
      propertyName: 'ticketStageID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: true,
    },
  ];

  public TicketsHistoryColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'ticketID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: 'תאריך פעולה',
      propertyName: 'updateDate',
      canSort: false,
      type: ColumnTypeEnum.DateTime,
      sortByServer: true,
    },
    {
      displayName: '',
      propertyName: 'ticketStatusID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: 'סטטוס',
      propertyName: 'ticketStatusName',
      canSort: true,
      type: ColumnTypeEnum.Tag,
      sortByServer: false,
      fieldId: 'ticketStatusID',
    },
    {
      displayName: 'שלב',
      propertyName: 'ticketStageName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      fieldId: 'ticketStageID',
      hasIcon: true,
    },
    {
      displayName: 'תת שלב',
      propertyName: 'ticketSubStageName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      fieldId: 'ticketSubStageID',
      hasIcon: true,
    },
    {
      displayName: 'תיאור פעולה',
      propertyName: 'description',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'ticketOwnerName',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      textOverflow: false,
    },
    {
      displayName: 'כתובת',
      propertyName: 'address',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'משתמש מערכת',
      propertyName: 'userName',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: '',
      propertyName: 'ticketStageID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: '',
      propertyName: 'ticketSubStageID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
  ];
}
