export enum InfrastructureEnumTitles {
  InfrastructureAreasTitle = 'טבלת אזורים',
  InfrastructureStreetsTitle = 'טבלת רחובות',
  InfrastructureSpecialTitle = 'מאגר רכבים מיוחדים',
  InfrastructureChipsTitle = 'שבבים',
  InfrastructurePlaintiffsCausesTitle = 'עילות תובע',
  InfrastructureSignsTitle = 'שלטים',
  InfrastructureBusinessTitle = 'עסקים',
  InfrastructureViolationsTitle = 'סעיפי עבירה',
  InfrastructureViolationsProcessTypesTitle = 'סעיפי עבירה-תהליכים',
  OwnerDialogTitle = 'פרטי הבעלים',
  PetDialogTitle = 'פרטי בעל חיים',
  EditDialogTitle = 'עריכת רשומה',
  AddDialogTitle = 'הוספת רשומה',
}

export enum InfrastructureEnumTexts {
    ExportFileTitle = 'יצוא מבנה קובץ',
    ImportFileTitle = 'יבוא קובץ',
    ExportFileDescription = 'קוד, תיאור, סטטוס קוד לאוטומציה',
    ImportFileDescription = 'קוד, ת.זהות, שם פרטי, שם משפחה, ישוב , רחוב, מספר בית, כניסה, דירה, מיקוד , טלפון, טלפון נייד, מייל',
    ExportFileIsSigns = 'טען קובץ שלטים',
    ExportFileIsSpecial = 'טען קובץ מאגר רכבים מיוחדים',
    ExportFileIsBusiness = 'טען קובץ עסקים',
    ExportFileIsViolations = 'טען קובץ סעיפי עבירה',
    ExportFileIsViolationsProcessTypes = 'טען קובץ סעיפי עבירה-תהליכים',
    ExportFileIsSubStages = 'טען קובץ סוגי משימות',
}

export enum InfrastructureEnumDialogs {
    StreetsDialogDiscription = `קוד, קוד הרחוב, מספרי בית זוגיים מ, מספרי בית זוגיים עד, מספרי בית אי זוגיים מ, מספרי בית אי זוגיים עד, שיוך לאזור תו דייר, שידור למסופון, שם רחוב קודם, חניה אסורה מ, חניה אסורה עד, חניה אסורה מ, חניה אסורה עד, חניה אסורה מ, חניה אסורה עד, זכאי לתו דייר מספרי בית זוגיים מ, זכאי לתו דייר מספרי בית זוגיים עד, זכאי לתו דייר מספרי בית אי זוגיים מ, זכאי לתו דייר מספרי בית אי זוגיים עד, היתר דקות לחניה רצופה, רישום דוח אזהרה, קוד עיר`,
    StreetsDialogImportDiscription = `קוד, תיאור, סטטוס קוד לאוטומציה`,
    ChipsDialogDiscription = `שבב,ת.ז,שם פרטי,שם משפחה,שבב,ת.זהות,שם פרטי,שם משפחה,רחוב,מספר בית,כניסה,דירה,ת.ד,ישוב,מיקוד,טלפון,טלפון 2,גזע,צבע,מין,שם,תאריך חיסון קודם,תאריך חיסון אחרון,שם וטרינר,מס' רישיון וטרינרי,תאריך לידה,מס' בעל חי, סטטוס בע''ח (1=נפטר 2=קיבל חיסון 3=שינוי בעלות),תאריך משלוח התראה`,
    ChipsDialogImportDiscription =  'קליטת קובץ שבבים',
    ChipsDialogExportDiscription = `קוד,מספר שבב,תעודת זהות,שם מלא בעלים,כתובת מלאה,תאריך עדכון`,
    CitizensDialogExportDiscription = `קוד, ת.זהות, שם פרטי, שם משפחה, ישוב , רחוב, מספר בית, כניסה, דירה, מיקוד , טלפון, טלפון נייד, מייל`,
    CitizensDialogImportDiscription = `קוד, ת.זהות, שם פרטי, שם משפחה, ישוב , רחוב, מספר בית, כניסה, דירה, מיקוד , טלפון, טלפון נייד, מייל`,
    ColorsDialogDiscription = `קוד,צבע,סטטוס,קוד לאוטומציה.`,
    SpecialDialogExportDisabledDiscription = `מספר רישוי, תאריך הנפקה, קוד סוג רכב`,
    SpecialDialogExportPublicDiscription = `מספר רישוי, תאריך הנפקה, קוד סוג רכב,קוד סוג היברידי`,
    SubStagesDialogDiscription = `קוד, תיאור, סטטוס, סוג, פעיל/לא פעיל`,
    TicketsSourceDialogExportDiscription = 'מקור קבלת דוח,קוד,שיטת מסירה,סוג דוח,הועבר לשלב',
    TollsDialogImportDiscription = 'קוד, תיאור אגרה,סכום אגרה,סוג אגרה ',   
    TollsDialogExportDiscription = 'קוד, תיאור אגרה,סכום אגרה,סוג אגרה ',
    TypesDialogImportDiscription = 'קוד, תיאור, סטטוס, קוד לאוטומציה.',
    TypesDialogExportDiscription = 'קוד, תיאור, סטטוס, קוד לאוטומציה.',
    ViolationsTypesDialogExportDiscription = 'קוד,תיאור,משויך לסוג דוח,קוד לאוטומציה,קוד ממשק למג"ק,קוד ממשק מטרופארק',
    BusinessDialogExportDiscription = 'קוד ,ח.פ , שם העסק , ישוב , רחוב , מספר בית , כניסה  ,דירה , ת.ד , מיקוד , טלפון, טלפון נייד, מייל',
    BusinessDialogImportDiscription = 'קוד ,ח.פ , שם העסק , ישוב , רחוב , מספר בית , כניסה  ,דירה , ת.ד , מיקוד , טלפון, טלפון נייד, מייל',
    ManufactureDialogExportDiscription = 'קוד, תיאור, סטטוס, קוד לאוטומציה.',
    ManufactureDialogImportDiscription = 'קוד, תיאור, סטטוס, קוד לאוטומציה.',
    PlaintiffsCausesDialogExportDiscription = 'קוד,תיאור,שיוך לקבוצה,סטטוס,הדפסת ספח,קוד מכתב חניה,קוד מכתב כללי,קוד מכתב מנהלי,סוג דוח,שיוך להחלטה',
    ViolationsDialogImportDiscription = 'קוד, תיאור, תיאור קצר, סוג דוח, קוד סוג עבירה, סעיף עבירה, סכום קנס מקור, קוד סוג תיק בית משפט, הערה, קוד לאוטומציה, קוד למטרופולינט, תו נכה, ת.ז,  מספר רישוי, ח.פ/ת.ז, מספר עותקים, הקמת דוח אמת לאחר פרק זמן, הערת מסופון, רישום אזהרה, קוד התראה, קוד עבירה.',
    ViolationsDialogExportDiscription = 'קוד, תיאור, תיאור קצר, סוג דוח, קוד סוג עבירה, סעיף עבירה, סכום קנס מקור, קוד סוג תיק בית משפט, הערה, קוד לאוטומציה, קוד למטרופולינט, תו נכה, ת.ז,  מספר רישוי, ח.פ/ת.ז, מספר עותקים, הקמת דוח אמת לאחר פרק זמן, הערת מסופון, רישום אזהרה, קוד התראה, קוד עבירה.',
    ViolationsProcessTypesDialogImportDiscription = 'קוד, תיאור, תיאור קצר, סוג דוח, קוד סוג עבירה, סעיף עבירה, סכום קנס מקור, קוד סוג תיק בית משפט, הערה, קוד לאוטומציה, קוד למטרופולינט, תו נכה, ת.ז,  מספר רישוי, ח.פ/ת.ז, מספר עותקים, הקמת דוח אמת לאחר פרק זמן, הערת מסופון, רישום אזהרה, קוד התראה, קוד עבירה.',
    ViolationsProcessTypesDialogExportDiscription = 'קוד, תיאור, תיאור קצר, סוג דוח, קוד סוג עבירה, סעיף עבירה, סכום קנס מקור, קוד סוג תיק בית משפט, הערה, קוד לאוטומציה, קוד למטרופולינט, תו נכה, ת.ז,  מספר רישוי, ח.פ/ת.ז, מספר עותקים, הקמת דוח אמת לאחר פרק זמן, הערת מסופון, רישום אזהרה, קוד התראה, קוד עבירה.',

}