import { inspectorEnforcementActionMap } from './../maps/userMaps';
import { ROUTE_PATH } from '../../constants/routerPath';
import { ModuleNames } from '../enum/moduleEnum';
import { InfrastructuresFiltersEnum } from '../../constants/InfrastructuresFiltersEnum';
import { ExternalInterfacesFiltersEnum } from '../../constants/ExternalInterfacesFiltersEnum';
import { LegalRequestsFiltersEnum } from '../../constants/LegalRequestsFiltersEnum';
import { PermissionRoutes } from '../../constants/permissions.enum';
import { Menu } from '../base/menu.model';
import { ConstPath } from '../../constants/const_path';

export class Menus {
  public static AdminSideMenu: Menu = {
    name: 'MainPage',
    menuItems: [
      {
        id: '1',
        path: '',
        displayName: ModuleNames.Dashboards,
        subDisplayName: ModuleNames.DashboardsSub,
        icon: 'dashboards-menu.svg',
        route: '',
        permissionRoute: [],
        menuItems: [],
        active: false,
        showItem: true,
      },
      {
        id: '2',
        path: ROUTE_PATH.TicketsNew.Home,
        displayName: ModuleNames.TicketsNewModule,
        icon: 'tickets-world-menu.svg',
        route: ROUTE_PATH.TicketsNew.Home,
        permissionRoute: [],
        menuItems: [],
        active: true,
        showItem: true,
      },
      // {
      //   id: '3',
      //   path: ROUTE_PATH.ParkingPermits.Home,
      //   displayName: ModuleNames.ParkingPermitsModule,
      //   icon: 'permits-world-menu.svg',
      //   route: ROUTE_PATH.ParkingPermits.Home,
      //   permissionRoute: [],
      //   active: true,
      //   showItem: true,
      // },
      {
        id: '3',
        path: ROUTE_PATH.ParkingPermits.Home,
        displayName: ModuleNames.ParkingPermitsModule,
        icon: 'permits-world-menu.svg',
        route: ROUTE_PATH.ParkingPermits.Home,
        permissionRoute: [],
        active: true,
        showItem: true,
        menuItems: [
          {
            id: '0',
            path: `${ROUTE_PATH.ParkingPermits.Home}`,
            displayName: ModuleNames.ParkingPermitsMain,
            route: `${ROUTE_PATH.ParkingPermits.Home}`,
            icon: 'productions-menu.svg',
          },
          {
            id: '1',
            path: `${ROUTE_PATH.ParkingPermits.Home}/${ROUTE_PATH.ParkingPermits.TypesMain}/${ROUTE_PATH.ParkingPermits.Types}`,
            displayName: ModuleNames.ParkingPermitsTypes,
            route: `${ROUTE_PATH.ParkingPermits.Home}/${ROUTE_PATH.ParkingPermits.TypesMain}/${ROUTE_PATH.ParkingPermits.Types}`,
            icon: 'productions-menu.svg',
          },

          {
            id: '2',
            path: `${ROUTE_PATH.ParkingPermits.Home}/${ROUTE_PATH.ParkingPermits.CreateNew}`,
            displayName: ModuleNames.ParkingPermitsCreate,
            route: `${ROUTE_PATH.ParkingPermits.Home}/${ROUTE_PATH.ParkingPermits.CreateNew}`,
            icon: 'productions-menu.svg',
          },
        ],
      },
      {
        id: '4',
        path: ROUTE_PATH.Notices.Home,
        displayName: ModuleNames.NoticesModule,
        icon: 'productions-menu.svg',
        route: ROUTE_PATH.Notices.Home,
        permissionRoute: [],
        menuItems: [
          {
            id: '1',
            path: ROUTE_PATH.Notices.Home,
            displayName: ModuleNames.NoticesModule,
            route: ROUTE_PATH.Notices.Home,
            icon: 'productions-menu.svg',
          },
          {
            id: '2',
            path: `${ROUTE_PATH.Notices.Home}/${ROUTE_PATH.Notices.Main}`,
            displayName: ModuleNames.NoticesMain,
            route: `${ROUTE_PATH.Notices.Home}/${ROUTE_PATH.Notices.Main}`,
            icon: 'productions-menu.svg',
          },
        ],
        active: true,
        showItem: true,
      },
      {
        id: '5',
        path: ROUTE_PATH.LegalRequests.Home,
        displayName: ModuleNames.LegalRequestsModule,
        icon: 'legal-department-menu.svg',
        route: ROUTE_PATH.LegalRequests.Home,
        permissionRoute: [],
        active: true,
        showItem: true,
        menuItems: [
          {
            id: '1',
            path: ROUTE_PATH.LegalRequests.Home,
            displayName: LegalRequestsFiltersEnum.AppealRequests,
            route: ROUTE_PATH.LegalRequests.Home,
            state: {
              name: LegalRequestsFiltersEnum.AppealRequests,
            },
            queryParams: [{ requestType: [2] }],
            icon: ConstPath.LEGAL_REQUESTS_APPEAL,
          },
          {
            id: '2',
            path: ROUTE_PATH.LegalRequests.Home,
            displayName: LegalRequestsFiltersEnum.JudgedRequests,
            route: ROUTE_PATH.LegalRequests.Home,
            state: {
              name: LegalRequestsFiltersEnum.JudgedRequests,
            },
            queryParams: [{ requestType: [4] }],
            icon: ConstPath.LEGAL_REQUESTS_COURT,
          },
          {
            id: '3',
            path: ROUTE_PATH.LegalRequests.Home,
            displayName: LegalRequestsFiltersEnum.ConversionRequests,
            route: ROUTE_PATH.LegalRequests.Home,
            state: {
              name: LegalRequestsFiltersEnum.ConversionRequests,
            },
            queryParams: [{ requestType: [1] }],
            icon: ConstPath.LEGAL_REQUESTS_HASAVA,
          },
        ],
      },
      // {
      //   id: '6',
      //   path: '',
      //   displayName: ModuleNames.Terminal,
      //   icon: 'terminal-menu.svg',
      //   route: '',
      //   permissionRoute: [],
      //   menuItems: [],
      //   active: false,
      // },

      {
        id: '6',
        path: ROUTE_PATH.Terminal.Home,
        displayName: ModuleNames.Msofon,
        icon: 'terminal-menu.svg',
        route: ROUTE_PATH.Terminal.Home,
        permissionRoute: [],
        active: true,
        menuItems: [
          {
            id: '0',
            path: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Notebooks}`,
            displayName: ModuleNames.NotebooksManagement,
            icon: 'terminal-menu.svg',
            route: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Notebooks}`,
            permissionRoute: [],
          },
          {
            id: '1',
            path: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Inspectors}`,
            displayName: ModuleNames.InspectorsManagement,
            icon: 'terminal-menu.svg',
            route: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Inspectors}`,
            permissionRoute: [],
          },
          {
            id: '2',
            path: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Messages}`,
            displayName: ModuleNames.TerminalInsperctorsMessagesComponent,
            icon: 'terminal-menu.svg',
            route: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Messages}`,
            permissionRoute: [],
          },
          {
            id: '3',
            path: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Settings}`,
            displayName: ModuleNames.TerminalSettings,
            icon: 'terminal-menu.svg',
            route: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Settings}`,
            permissionRoute: [],
          },
          {
            id: '4',
            path: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Statistics}`,
            displayName: ModuleNames.TerminalStatistics,
            icon: 'terminal-menu.svg',
            route: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Statistics}`,
            permissionRoute: [],
          },
        ],
        showItem: true,
      },
      {
        id: '7',
        path: '',
        displayName: ModuleNames.RegisterAndPayments,
        icon: 'register-payments-menu.svg',
        route: '',
        permissionRoute: [],
        menuItems: [],
        active: false,
        showItem: true,
      },
      {
        id: '8',
        path: '',
        displayName: ModuleNames.Modules,
        icon: 'terminal-menu.svg',
        route: '',
        permissionRoute: [],
        menuItems: [],
        active: false,
        showItem: true,
      },
      {
        id: '9',
        path: ROUTE_PATH.Enforcement.Home,
        displayName: ModuleNames.Enforcement,
        icon: 'enforcement-menu.svg',
        route: ROUTE_PATH.Enforcement.Home,
        permissionRoute: [],
        menuItems: [],
        active: false,
        showItem: true,
      },
      {
        id: '10',
        path: ROUTE_PATH.Infrastructure.Home,
        displayName: ModuleNames.InfrastructureLocalModule,
        subDisplayName: ModuleNames.Local,
        icon: 'infrastructure-menu.svg',
        route: ROUTE_PATH.Infrastructure.Home,
        active: true,
        showItem: true,
        menuItems: [
          {
            id: '1',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Streets}`,
            displayName: ModuleNames.Streets,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Streets}`,
            state: {
              name: InfrastructuresFiltersEnum.Streets,
            },
            icon: ConstPath.INFRASTRUCTURE_STREETS,
          },
          {
            id: '2',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Areas}`,
            displayName: ModuleNames.Areas,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Areas}`,
            state: {
              name: InfrastructuresFiltersEnum.Areas,
            },
            icon: ConstPath.INFRASTRUCTURE_AREAS,
          },
          {
            id: '3',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Citizens}`,
            displayName: ModuleNames.Citizens,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Citizens}`,
            icon: ConstPath.INFRASTRUCTURE_CITIZENS,
          },
          {
            id: '4',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.PlaintiffsCauses}`,
            displayName: ModuleNames.PlaintiffsCauses,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.PlaintiffsCauses}`,
            icon: ConstPath.INFRASTRUCTURE_PLAINTIFF_CAUSES,
          },
          {
            id: '5',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Signs}`,
            displayName: ModuleNames.Signs,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Signs}`,
            icon: ConstPath.INFRASTRUCTURE_SIGNS,
          },
          {
            id: '6',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Violations}`,
            displayName: ModuleNames.Violations,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Violations}`,
            state: {
              name: InfrastructuresFiltersEnum.Violations,
            },
            icon: ConstPath.INFRASTRUCTURE_VIOLATIONS,
          },
          {
            id: '7',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Business}`,
            displayName: ModuleNames.Business,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Business}`,
            icon: ConstPath.INFRASTRUCTURE_BUSINESS,
          },
          {
            id: '8',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Tolls}`,
            displayName: ModuleNames.Tolls,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Tolls}`,
            state: {
              name: InfrastructuresFiltersEnum.Tolls,
            },
            icon: ConstPath.INFRASTRUCTURE_TOLLS,
          },
        ],
      },
      {
        id: '11',
        path: ROUTE_PATH.Infrastructure.Home,
        displayName: ModuleNames.InfrastructureAdminModule,
        subDisplayName: ModuleNames.CountryWide,
        icon: 'infrastructure-menu.svg',
        route: ROUTE_PATH.Infrastructure.Home,
        active: true,
        showItem: true,
        menuItems: [
          {
            id: '1',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Main}`,
            displayName: ModuleNames.VehiclesInfrastructure,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Main}`,
            state: {
              name: InfrastructuresFiltersEnum.Vehicles,
            },
            icon: ConstPath.INFRASTRUCTURE_VEHICLES,
          },

          {
            id: '2',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.SubStages}`,
            displayName: ModuleNames.SubStages,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.SubStages}`,
            state: {
              name: InfrastructuresFiltersEnum.SubStages,
            },
            icon: ConstPath.INFRASTRUCTURE_SUB_STAGES,
          },
          {
            id: '3',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Violation}`,
            displayName: ModuleNames.ViolationTypes,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Violation}`,
            state: {
              name: InfrastructuresFiltersEnum.ViolationTypes,
            },
            icon: ConstPath.INFRASTRUCTURE_VIOLATION_TYPES,
          },

          {
            id: '4',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.TicketsSource}`,
            displayName: ModuleNames.TicketsSource,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.TicketsSource}`,
            state: {
              name: InfrastructuresFiltersEnum.TicketsSource,
            },
            icon: ConstPath.INFRASTRUCTURE_TICKET_SOURCE,
          },
          {
            id: '5',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.TicketsStagesStatuses}`,
            displayName: ModuleNames.TicketsStagesStatuses,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.TicketsStagesStatuses}`,
            icon: ConstPath.INFRASTRUCTURE_STAGES_STATUES,
          },
          {
            id: '6',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Chips}`,
            displayName: ModuleNames.Chips,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Chips}`,
            icon: ConstPath.INFRASTRUCTURE_CHIPS,
          },
          {
            id: '7',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Special}`,
            displayName: ModuleNames.Special,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Special}`,
            state: {
              name: InfrastructuresFiltersEnum.Special,
            },
            icon: ConstPath.INFRASTRUCTURE_SPECIAL_VEHICLES,
          },
        ],
      },

      {
        id: '12',
        path: ROUTE_PATH.Management.Home,
        displayName: ModuleNames.Settings,
        icon: 'municipal-menu.svg',
        route: ROUTE_PATH.Management.Home,
        permissionRoute: [],
        active: true,
        showItem: true,
        menuItems: [
          {
            id: '1',
            path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}`,
            displayName: ModuleNames.TimelineSettings,
            route: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}`,
            permissionRoute: [],
            icon: ConstPath.TIMELINE,
          },
          {
            id: '2',
            path: `${ROUTE_PATH.InventoryManagement.Home}`,
            displayName: ModuleNames.InventoryManagement,
            route: ROUTE_PATH.InventoryManagement.Home,
            permissionRoute: [],
            icon: ConstPath.INVENTORY,
          },
          {
            id: '3',
            path: `${ROUTE_PATH.Management.Home}/create/${ROUTE_PATH.Management.Authority}`,
            displayName: ModuleNames.AuthorityCreate,
            route: `${ROUTE_PATH.Management.Home}/create/${ROUTE_PATH.Management.Authority}`,
            permissionRoute: [],
            icon: ConstPath.INVENTORY,
            active: false,
          },
          {
            id: '4',
            path: `${ROUTE_PATH.Management.Home}/edit/${ROUTE_PATH.Management.Authority}`,
            displayName: ModuleNames.AuthoritySettings,
            route: `${ROUTE_PATH.Management.Home}/edit/${ROUTE_PATH.Management.Authority}`,
            permissionRoute: [],
            icon: ConstPath.INVENTORY,
            active: false,
          },
          {
            id: '5',
            path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.DraftsAndLetters}`,
            displayName: ModuleNames.DraftsAndLetters,
            route: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.DraftsAndLetters}`,
            permissionRoute: [],
            icon: ConstPath.INVENTORY,
          },
          // {
          //   id: '6',
          //   path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.DraftsAndLetters}/${ROUTE_PATH.Management.CreateLetter}`,
          //   displayName: ModuleNames.DraftsAndLettersNewLetter,
          //   route: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.DraftsAndLetters}/${ROUTE_PATH.Management.CreateLetter}`,
          //   permissionRoute: [],
          //   icon: ConstPath.INVENTORY,
          // },
        ],
      },

      {
        id: '13',
        path: ROUTE_PATH.UsersPermissions.Home,
        displayName: ModuleNames.UsersPermissions,
        icon: 'users-permissions-menu.svg',
        route: ROUTE_PATH.UsersPermissions.Home,
        permissionRoute: [],
        active: true,
        showItem: true,
        menuItems: [
          {
            id: '1',
            path: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.Users}`,
            displayName: ModuleNames.Users,
            route: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.Users}`,
            state: {
              name: InfrastructuresFiltersEnum.Vehicles,
            },
            icon: ConstPath.USERS_LOCAL,
          },
          {
            id: '2',
            path: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.NationalUsers}`,
            displayName: ModuleNames.NationalUsers,
            route: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.NationalUsers}`,
            state: {
              name: InfrastructuresFiltersEnum.Vehicles,
            },
            icon: ConstPath.USERS_NATIONAL,
          },
          {
            id: '3',
            path: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.Permissions}`,
            displayName: ModuleNames.Permissions,
            route: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.Permissions}`,
            state: {
              name: InfrastructuresFiltersEnum.Vehicles,
            },
            icon: ConstPath.PERMISSIONS,
          },
          {
            id: '4',
            path: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.ParkingPermitsManagement}`,
            displayName: ModuleNames.Management,
            route: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.ParkingPermitsManagement}`,
            state: {
              name: InfrastructuresFiltersEnum.Vehicles,
            },
            icon: ConstPath.PERMITS,
          },
        ],
      },

      {
        id: '14',
        path: '',
        displayName: ModuleNames.InterfacesModule,
        icon: 'interfaces-menu.svg',
        route: '',
        permissionRoute: [],
        showItem: true,
        active: false,
        menuItems: [
          {
            id: '1',
            path: ROUTE_PATH.MinistyOfTransport.Home,
            displayName: ModuleNames.MinistryOfTransportModule,
            route: ROUTE_PATH.MinistyOfTransport.Home,
            state: {
              name: ExternalInterfacesFiltersEnum.MinistyOfTransport,
            },
            queryParams: [{ requestType: [1] }],
            permissionRoute: [],
            icon: ConstPath.TRANSPORT,
          },
          {
            id: '2',
            path: ROUTE_PATH.MinistryOfInterior.Home,
            displayName: ModuleNames.MinistryOfInteriorModule,
            route: ROUTE_PATH.MinistryOfInterior.Home,
            state: {
              name: ExternalInterfacesFiltersEnum.MinistryOfInterior,
            },
            queryParams: [{ requestType: [2] }],
            permissionRoute: [],
            icon: ConstPath.INTERIOR,
          },
          {
            id: '3',
            path: ROUTE_PATH.ProsecutorCaseSettings.Home,
            displayName: ModuleNames.ProsecutorCaseSettings,
            route: ROUTE_PATH.ProsecutorCaseSettings.Home,
            permissionRoute: [],
            icon: ConstPath.PROSECUTOR,
          },
        ],
      },
      {
        id: '15',
        path: '',
        displayName: ModuleNames.Legend,
        icon: 'legend-menu.svg',
        route: '',
        permissionRoute: [],
        menuItems: [],
        active: false,
      },
      // {
      //   id: '16',
      //   path: 'tickets-new/main',
      //   displayName: ModuleNames.BackOfficeSummary,
      //   icon: 'dashboards-menu.svg',
      //   route: 'tickets-new/main',
      //   permissionRoute: [],
      //   menuItems: [],
      //   active: true,
      //   showItem: true,
      // },
      // {
      //   id: '17',
      //   path: ROUTE_PATH.Dispatcher.Dispatcher,
      //   displayName: ModuleNames.TicketsSummary,
      //   icon: 'dashboards-menu.svg',
      //   route: 'dispatcher',
      //   permissionRoute: [],
      //   menuItems: [],
      //   active: true,
      //   showItem: true,
      // },
      // {
      //   id: '18',
      //   path: ROUTE_PATH.Management.TicketsGenerator,
      //   displayName: ModuleNames.TicketsGenerator,
      //   icon: 'tickets-world-menu.svg',
      //   route: ROUTE_PATH.Management.TicketsGenerator,
      //   permissionRoute: [],
      //   menuItems: [],
      //   active: true,
      //   showItem: true,
      // },
      // {
      //   id: '19',
      //   path: ROUTE_PATH.AI.Main,
      //   displayName: ModuleNames.AIHotfix,
      //   icon: 'dashboards-menu.svg',
      //   route: ROUTE_PATH.AI.Main,
      //   permissionRoute: [],
      //   menuItems: [],
      //   active: true,
      //   showItem: true,
      // },
    ],
  };

  public static SideMenu: Menu = {
    name: 'MainPage',
    menuItems: [
      {
        id: '1',
        path: '',
        displayName: ModuleNames.Dashboards,
        subDisplayName: ModuleNames.DashboardsSub,
        icon: 'dashboards-menu.svg',
        route: '',
        permissionRoute: [],
        menuItems: [],
        active: false,
      },
      {
        id: '2',
        path: ROUTE_PATH.TicketsNew.Home,
        displayName: ModuleNames.TicketsNewModule,
        icon: 'tickets-world-menu.svg',
        route: ROUTE_PATH.TicketsNew.Home,
        permissionRoute: [PermissionRoutes.TICKETS_GET_TICKETS],
        menuItems: [],
        active: true,
      },
      {
        id: '3',
        path: ROUTE_PATH.ParkingPermits.Home,
        displayName: ModuleNames.ParkingPermitsModule,
        icon: 'permits-world-menu.svg',
        route: ROUTE_PATH.ParkingPermits.Home,
        permissionRoute: [PermissionRoutes.PARKING_PERMIT],
        active: true,
        menuItems: [
          {
            id: '0',
            path: `${ROUTE_PATH.ParkingPermits.Home}`,
            displayName: ModuleNames.ParkingPermitsModule,
            route: `${ROUTE_PATH.ParkingPermits.Home}`,
            icon: 'productions-menu.svg',
          },
          {
            id: '1',
            path: `${ROUTE_PATH.ParkingPermits.Home}/${ROUTE_PATH.ParkingPermits.TypesMain}`,
            displayName: ModuleNames.ParkingPermitsTypes,
            route: `${ROUTE_PATH.ParkingPermits.Home}/${ROUTE_PATH.ParkingPermits.TypesMain}`,
            icon: 'productions-menu.svg',
          },
          {
            id: '2',
            path: `${ROUTE_PATH.ParkingPermits.Home}/create/${ROUTE_PATH.ParkingPermits.CreateUpdateMain}`,
            displayName: ModuleNames.ParkingPemitsTypesCreate,
            route: `${ROUTE_PATH.ParkingPermits.Home}/create/${ROUTE_PATH.ParkingPermits.CreateUpdateMain}`,
            icon: 'productions-menu.svg',
          },
          {
            id: '3',
            path: `${ROUTE_PATH.ParkingPermits.Home}/${ROUTE_PATH.ParkingPermits.CreateNew}`,
            displayName: ModuleNames.ParkingPermitsCreate,
            route: `${ROUTE_PATH.ParkingPermits.Home}/${ROUTE_PATH.ParkingPermits.CreateNew}`,
            icon: 'productions-menu.svg',
          },
        ],
      },
      {
        id: '4',
        path: ROUTE_PATH.Notices.Home,
        displayName: ModuleNames.NoticesModule,
        icon: 'productions-menu.svg',
        route: ROUTE_PATH.Notices.Home,
        permissionRoute: [],
        menuItems: [
          {
            id: '1',
            path: ROUTE_PATH.Notices.Home,
            displayName: ModuleNames.NoticesModule,
            route: ROUTE_PATH.Notices.Home,
            icon: 'productions-menu.svg',
          },
          {
            id: '2',
            path: `${ROUTE_PATH.Notices.Home}/${ROUTE_PATH.Notices.Main}`,
            displayName: ModuleNames.NoticesMain,
            route: `${ROUTE_PATH.Notices.Home}/${ROUTE_PATH.Notices.Main}`,
            icon: 'productions-menu.svg',
          },
        ],
        active: true,
        showItem: true,
      },
      {
        id: '5',
        path: ROUTE_PATH.LegalRequests.Home,
        displayName: ModuleNames.LegalRequestsModule,
        icon: 'legal-department-menu.svg',
        route: ROUTE_PATH.LegalRequests.Home,
        permissionRoute: [PermissionRoutes.LEGAL_REQUEST_SUMMARY],
        active: true,
        showItem: true,
        menuItems: [
          {
            id: '1',
            path: ROUTE_PATH.LegalRequests.Home,
            displayName: LegalRequestsFiltersEnum.AppealRequests,
            route: ROUTE_PATH.LegalRequests.Home,
            state: {
              name: LegalRequestsFiltersEnum.AppealRequests,
            },
            queryParams: [{ requestType: [2] }],
            icon: 'temp.svg',
          },
          {
            id: '2',
            path: ROUTE_PATH.LegalRequests.Home,
            displayName: LegalRequestsFiltersEnum.JudgedRequests,
            route: ROUTE_PATH.LegalRequests.Home,
            state: {
              name: LegalRequestsFiltersEnum.JudgedRequests,
            },
            queryParams: [{ requestType: [4] }],
            icon: 'temp.svg',
          },
          {
            id: '3',
            path: ROUTE_PATH.LegalRequests.Home,
            displayName: LegalRequestsFiltersEnum.ConversionRequests,
            route: ROUTE_PATH.LegalRequests.Home,
            state: {
              name: LegalRequestsFiltersEnum.ConversionRequests,
            },
            queryParams: [{ requestType: [1] }],
            icon: 'temp.svg',
          },
        ],
      },
      {
        id: '6',
        path: ROUTE_PATH.Terminal.Home,
        displayName: ModuleNames.Msofon,
        icon: 'terminal-menu.svg',
        route: ROUTE_PATH.Terminal.Home,
        permissionRoute: [PermissionRoutes.INFRASTRUCTURE_TABLES],
        active: true,
        menuItems: [
          {
            id: '0',
            path: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Notebooks}`,
            displayName: ModuleNames.NotebooksManagement,
            icon: 'terminal-menu.svg',
            route: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Notebooks}`,
            permissionRoute: [],
          },
          {
            id: '1',
            path: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Inspectors}`,
            displayName: ModuleNames.InspectorsManagement,
            icon: 'terminal-menu.svg',
            route: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Inspectors}`,
            permissionRoute: [],
          },
          {
            id: '2',
            path: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Messages}`,
            displayName: ModuleNames.TerminalInsperctorsMessagesComponent,
            icon: 'terminal-menu.svg',
            route: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Messages}`,
            permissionRoute: [],
          },
          {
            id: '3',
            path: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Settings}`,
            displayName: ModuleNames.TerminalSettings,
            icon: 'terminal-menu.svg',
            route: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Settings}`,
            permissionRoute: [],
          },
          {
            id: '4',
            path: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Statistics}`,
            displayName: ModuleNames.TerminalStatistics,
            icon: 'terminal-menu.svg',
            route: `${ROUTE_PATH.Terminal.Home}/${ROUTE_PATH.Terminal.Statistics}`,
            permissionRoute: [],
          },
        ],
        showItem: true,
      },
      {
        id: '7',
        path: '',
        displayName: ModuleNames.RegisterAndPayments,
        icon: 'register-payments-menu.svg',
        route: '',
        permissionRoute: [],
        menuItems: [],
        active: false,
      },
      {
        id: '8',
        path: '',
        displayName: ModuleNames.Modules,
        icon: 'terminal-menu.svg',
        route: '',
        permissionRoute: [],
        menuItems: [],
        active: false,
      },
      {
        id: '9',
        path: ROUTE_PATH.Enforcement.Home,
        displayName: ModuleNames.Enforcement,
        icon: 'enforcement-menu.svg',
        route: ROUTE_PATH.Enforcement.Home,
        permissionRoute: [],
        menuItems: [],
        active: false,
      },
      {
        id: '10',
        path: ROUTE_PATH.Infrastructure.Home,
        displayName: ModuleNames.InfrastructureLocalModule,
        subDisplayName: ModuleNames.Local,
        icon: 'infrastructure-menu.svg',
        route: ROUTE_PATH.Infrastructure.Home,
        active: true,

        permissionRoute: [PermissionRoutes.INFRASTRUCTURE_TABLES],
        menuItems: [
          {
            id: '1',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Streets}`,
            displayName: ModuleNames.Streets,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Streets}`,
            state: {
              name: InfrastructuresFiltersEnum.Streets,
            },
          },
          {
            id: '2',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Areas}`,
            displayName: ModuleNames.Areas,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Areas}`,
            state: {
              name: InfrastructuresFiltersEnum.Areas,
            },
          },
          {
            id: '3',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Citizens}`,
            displayName: ModuleNames.Citizens,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Citizens}`,
          },
          {
            id: '4',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.PlaintiffsCauses}`,
            displayName: ModuleNames.PlaintiffsCauses,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.PlaintiffsCauses}`,
          },
          {
            id: '5',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Signs}`,
            displayName: ModuleNames.Signs,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Signs}`,
          },
          {
            id: '6',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Violations}`,
            displayName: ModuleNames.Violations,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Violations}`,
            state: {
              name: InfrastructuresFiltersEnum.Violations,
            },
          },
          {
            id: '7',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Business}`,
            displayName: ModuleNames.Business,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Business}`,
          },
          {
            id: '8',
            path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Tolls}`,
            displayName: ModuleNames.Tolls,
            route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Tolls}`,
            state: {
              name: InfrastructuresFiltersEnum.Tolls,
            },
          },
        ],
      },
      // {
      //   id: '11',
      //   path: ROUTE_PATH.Infrastructure.Home,
      //   displayName: ModuleNames.InfrastructureAdminModule,
      //   subDisplayName: ModuleNames.CountryWide,
      //   icon: 'infrastructure-menu.svg',
      //   route: ROUTE_PATH.Infrastructure.Home,
      //   active: true,

      //   menuItems: [
      //     {
      //       id: '1',
      //       path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.VehiclesType}`,
      //       displayName: ModuleNames.VehiclesInfrastructure,
      //       route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.VehiclesType}`,
      //       state: {
      //         name: InfrastructuresFiltersEnum.Vehicles,
      //       },
      //     },
      //     {
      //       id: '2',
      //       path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.SubStages}`,
      //       displayName: ModuleNames.SubStages,
      //       route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.SubStages}`,
      //       state: {
      //         name: InfrastructuresFiltersEnum.SubStages,
      //       },
      //     },
      //     {
      //       id: '3',
      //       path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Violation}`,
      //       displayName: ModuleNames.ViolationTypes,
      //       route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Violation}`,
      //       state: {
      //         name: InfrastructuresFiltersEnum.ViolationTypes,
      //       },
      //     },

      //     {
      //       id: '4',
      //       path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.TicketsSource}`,
      //       displayName: ModuleNames.TicketsSource,
      //       route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.TicketsSource}`,
      //       state: {
      //         name: InfrastructuresFiltersEnum.TicketsSource,
      //       },
      //     },
      //     {
      //       id: '5',
      //       path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.TicketsStagesStatuses}`,
      //       displayName: ModuleNames.TicketsStagesStatuses,
      //       route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.TicketsStagesStatuses}`,
      //     },
      //     {
      //       id: '6',
      //       path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Chips}`,
      //       displayName: ModuleNames.Chips,
      //       route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Chips}`,
      //     },
      //     {
      //       id: '7',
      //       path: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Special}`,
      //       displayName: ModuleNames.Special,
      //       route: `${ROUTE_PATH.Infrastructure.Home}/${ROUTE_PATH.Infrastructure.Special}`,
      //       state: {
      //         name: InfrastructuresFiltersEnum.Special,
      //       },
      //     },
      //   ],
      // },

      {
        id: '12',
        path: ROUTE_PATH.Management.Home,
        displayName: ModuleNames.Settings,
        icon: 'municipal-menu.svg',
        route: ROUTE_PATH.Management.Home,
        permissionRoute: [PermissionRoutes.INFRASTRUCTURE_TABLES],
        active: true,
        showItem: true,
        menuItems: [
          {
            id: '1',
            path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}`,
            displayName: ModuleNames.TimelineSettings,
            route: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}`,
            permissionRoute: [],
          },
          {
            id: '2',
            path: `${ROUTE_PATH.InventoryManagement.Home}`,
            displayName: ModuleNames.InventoryManagement,
            route: ROUTE_PATH.InventoryManagement.Home,
            permissionRoute: [],
          },
          {
            id: '3',
            path: `${ROUTE_PATH.Management.Home}/edit/${ROUTE_PATH.Management.Authority}`,
            displayName: ModuleNames.AuthoritySettings,
            route: `${ROUTE_PATH.Management.Home}/edit/${ROUTE_PATH.Management.Authority}`,
            permissionRoute: [PermissionRoutes.INFRASTRUCTURE_TABLES],
            icon: ConstPath.INVENTORY,
            active: false,
          },
          {
            id: '4',
            path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.DraftsAndLetters}`,
            displayName: ModuleNames.DraftsAndLetters,
            route: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.DraftsAndLetters}`,
            permissionRoute: [],
            icon: ConstPath.INVENTORY,
          },
          // {
          //   id: '3',
          //   path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.DraftsAndLetters}`,
          //   displayName: ModuleNames.DraftsAndLetters,
          //   route: `${ROUTE_PATH.Management.Home}/ ${ROUTE_PATH.Management.DraftsAndLetters}`,
          //   permissionRoute: [],
          //   icon: ConstPath.INVENTORY,
          // },
        ],
      },

      {
        id: '13',
        path: ROUTE_PATH.UsersPermissions.Home,
        displayName: ModuleNames.UsersPermissions,
        icon: 'users-permissions-menu.svg',
        route: ROUTE_PATH.UsersPermissions.Home,
        permissionRoute: [PermissionRoutes.USERS_LOCAL],
        active: true,

        menuItems: [
          {
            id: '1',
            path: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.Users}`,
            displayName: ModuleNames.Users,
            route: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.Users}`,
            state: {
              name: InfrastructuresFiltersEnum.Vehicles,
            },
          },
          // {
          //   id: '2',
          //   path: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.NationalUsers}`,
          //   displayName: ModuleNames.NationalUsers,
          //   route: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.NationalUsers}`,
          //   state: {
          //     name: InfrastructuresFiltersEnum.Vehicles,
          //   },
          // },
          // {
          //   id: '3',
          //   path: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.Permissions}`,
          //   displayName: ModuleNames.Permissions,
          //   route: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.Permissions}`,
          //   state: {
          //     name: InfrastructuresFiltersEnum.Vehicles,
          //   },
          // },
          {
            id: '4',
            path: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.ParkingPermitsManagement}`,
            displayName: ModuleNames.Management,
            route: `${ROUTE_PATH.UsersPermissions.Home}/${ROUTE_PATH.UsersPermissions.ParkingPermitsManagement}`,
            state: {
              name: InfrastructuresFiltersEnum.Vehicles,
            },
          },
        ],
      },

      {
        id: '14',
        path: '',
        displayName: ModuleNames.InterfacesModule,
        icon: 'interfaces-menu.svg',
        route: '',
        active: false,
        permissionRoute: [],
        menuItems: [
          {
            id: '1',
            path: ROUTE_PATH.MinistyOfTransport.Home,
            displayName: ModuleNames.MinistryOfTransportModule,
            route: ROUTE_PATH.MinistyOfTransport.Home,
            state: {
              name: ExternalInterfacesFiltersEnum.MinistyOfTransport,
            },
            queryParams: [{ requestType: [1] }],
            permissionRoute: [],
          },
          {
            id: '2',
            path: ROUTE_PATH.MinistryOfInterior.Home,
            displayName: ModuleNames.MinistryOfInteriorModule,
            route: ROUTE_PATH.MinistryOfInterior.Home,
            state: {
              name: ExternalInterfacesFiltersEnum.MinistryOfInterior,
            },
            queryParams: [{ requestType: [2] }],
            permissionRoute: [],
          },
          {
            id: '3',
            path: ROUTE_PATH.ProsecutorCaseSettings.Home,
            displayName: ModuleNames.ProsecutorCaseSettings,
            route: ROUTE_PATH.ProsecutorCaseSettings.Home,
            permissionRoute: [],
          },
        ],
      },
      {
        id: '15',
        path: '',
        displayName: ModuleNames.Legend,
        icon: 'legend-menu.svg',
        route: '',
        permissionRoute: [],
        menuItems: [],
        active: false,
      },
      // {
      //   id: '16',
      //   path: 'tickets-new/main',
      //   displayName: ModuleNames.BackOfficeSummary,
      //   // displayName: ModuleNames.TicketsSummary,
      //   icon: 'dashboards-menu.svg',
      //   route: 'tickets-new/main',
      //   permissionRoute: [],
      //   menuItems: [],
      //   active: true,
      //   showItem: true,
      // },
      // {
      //   id: '17',
      //   path: 'dispatcher',
      //   displayName: ModuleNames.TicketsSummary,
      //   icon: 'dashboards-menu.svg',
      //   route: 'dispatcher',
      //   permissionRoute: [],
      //   menuItems: [],
      //   active: true,
      //   showItem: true,
      // },
      // {
      //   id: '18',
      //   path: ROUTE_PATH.AI.Main,
      //   displayName: ModuleNames.AIHotfix,
      //   icon: 'dashboards-menu.svg',
      //   route: ROUTE_PATH.AI.Main,
      //   permissionRoute: [],
      //   menuItems: [],
      //   active: true,
      //   showItem: true,
      // },
    ],
  };
}
