import { Column, ColumnTypeEnum } from '../table';

export class MinistryOfTransportTable {
  public MinistryOfTransporMainColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'ticketID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: true,
    },

    // {
    //   displayName: '',
    //   propertyName: 'ticketStageID',
    //   canSort: false,
    //   type: ColumnTypeEnum.Hidden,
    //   sortByServer: false,
    // },
    {
      displayName: '',
      propertyName: 'ticketID',
      canSort: false,
      type: ColumnTypeEnum.Checkbox,
      sortByServer: false,
    },
    {
      displayName: 'מספר דוח',
      propertyName: 'ticketNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'מספר זהות',
      propertyName: 'nid',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'name',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
      textOverflow: true,
    },
    {
      displayName: 'סוג דוח',
      propertyName: 'ticketTypeName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: '',
      propertyName: 'ticketStatusID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: true,
    },
    {
      displayName: 'סטטוס',
      propertyName: 'ticketStatusName',
      canSort: true,
      type: ColumnTypeEnum.Tag,
      sortByServer: true,
      fieldId: 'ticketStatusID',
    },
    {
      displayName: 'שלב',
      propertyName: 'ticketStageName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
      fieldId: 'ticketStageID',
      hasIcon: true,
    },
    {
      displayName: 'יתרה לתשלום',
      propertyName: 'paymentBalance',
      canSort: true,
      type: ColumnTypeEnum.Currency,
      sortByServer: true,
      textColor: 'blue',
    },
    {
      displayName: 'תאריך יצירת דוח',
      propertyName: 'ticketGivingDate',
      canSort: true,
      type: ColumnTypeEnum.Date,
      sortByServer: true,
    },
    {
      displayName: 'תאריך עבירה',
      propertyName: 'violationDate',
      canSort: true,
      type: ColumnTypeEnum.Date,
      sortByServer: true,
    },
    {
      displayName: 'דוחות נוספים',
      propertyName: 'additionalTicketPaymentBalance',
      canSort: false,
      type: ColumnTypeEnum.Currency,
      sortByServer: true,
      textColor: 'black',
    },
    {
      displayName: 'רשות',
      propertyName: 'authorityName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: '',
      propertyName: 'ticketStageID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: true,
    },
  ];
}
