import { Column, ColumnTypeEnum } from '../table';

export class ParkingPermitTable {
  public static ParkingPermitColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'parkingPermitID',
      canSort: false,
      type: ColumnTypeEnum.Radio,
      sortByServer: true,
    },
    {
      displayName: 'מספר תו',
      propertyName: 'parkingPermitNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'מספר רכב',
      propertyName: 'vehicle.vehicleNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'מספר זהות',
      propertyName: 'citizen.nid',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'citizen.fullName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'כתובת',
      propertyName: 'citizen.homeAddress.fullAddress',
      sortField: 'citizen.citizenAddresses',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
      textOverflow: true,
    },
    {
      displayName: 'אזור/רחוב',
      propertyName: 'parkingPermitAreasString',
      sortField: 'areaNameAndStreetName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
      textOverflow: true,
    },
    {
      displayName: 'בתוקף מ',
      propertyName: 'startDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'פג תוקף',
      propertyName: 'expirationDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'סוג תו',
      propertyName: 'permitType.name',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'סטטוס',
      propertyName: 'parkingPermitStatus.name',
      fieldId: 'parkingPermitStatus.statusId',
      canSort: true,
      type: ColumnTypeEnum.Tag,
      sortByServer: true,
    },
    {
      displayName: 'ת. קליטה',
      propertyName: 'requestDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
  ];

  public static MainColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'parkingPermitID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: 'מספר תו',
      propertyName: 'parkingPermitNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'מספר רכב',
      propertyName: 'vehicle.vehicleNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'מספר זהות',
      propertyName: 'citizen.nid',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'citizen.fullName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'כתובת',
      propertyName: 'citizen.homeAddress.fullAddress',
      sortField: 'citizen.citizenAddresses',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      textOverflow: true,
    },
    {
      displayName: 'אזור/רחוב',
      propertyName: 'parkingPermitAreasString',
      sortField: 'areaNameAndStreetName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      textOverflow: true,
    },
    {
      displayName: 'בתוקף מ',
      propertyName: 'startDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'פג תוקף',
      propertyName: 'expirationDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'סוג תו',
      propertyName: 'permitType.name',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'סטטוס',
      propertyName: 'parkingPermitStatus.name',
      fieldId: 'parkingPermitStatus.statusId',
      canSort: true,
      type: ColumnTypeEnum.Tag,
      sortByServer: false,
    },
    {
      displayName: 'ת. קליטה',
      propertyName: 'requestDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
  ];
}
