import { Column, ColumnTypeEnum } from '../table';

export class ParkingPermitTable {
  public static ParkingPermitColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'parkingPermitID',
      canSort: false,
      type: ColumnTypeEnum.Radio,
      sortByServer: true,
      radioConfig: {
        // Single radio button per row; shared name across rows ensures single selection
        name: 'parkingPermitRowSelect',
        options: [{ value: 'parkingPermitID', label: '' }],
        type: 'default',
        direction: 'horizontal',
      },
    },
    {
      displayName: 'מספר תו',
      propertyName: 'parkingPermitNumber',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'מספר רכב',
      propertyName: 'vehicle.vehicleNumber',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'מספר זהות',
      propertyName: 'citizen.nid',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'citizen.fullName',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'כתובת',
      propertyName: 'citizen.homeAddress.fullAddress',
      sortField: 'citizen.citizenAddresses',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
      textOverflow: true,
    },
    {
      displayName: 'אזור/רחוב',
      propertyName: 'parkingPermitAreasString',
      sortField: 'areaNameAndStreetName',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
      textOverflow: true,
    },
    {
      displayName: 'בתוקף מ',
      propertyName: 'startDate',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'פג תוקף',
      propertyName: 'expirationDate',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'סוג תו',
      propertyName: 'permitType.name',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'סטטוס',
      propertyName: 'parkingPermitStatus.name',
      fieldId: 'parkingPermitStatus.statusId',
      canSort: false,
      type: ColumnTypeEnum.Tag,
      sortByServer: true,
    },
    {
      displayName: 'ת. קליטה',
      propertyName: 'requestDate',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
  ];

  public static MainColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'parkingPermitID',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: false,
    },
    {
      displayName: 'מספר תו',
      propertyName: 'parkingPermitNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'מספר רכב',
      propertyName: 'vehicle.vehicleNumber',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'מספר זהות',
      propertyName: 'citizen.nid',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'שם מלא',
      propertyName: 'citizen.fullName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'כתובת',
      propertyName: 'citizen.homeAddress.fullAddress',
      sortField: 'citizen.citizenAddresses',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      textOverflow: true,
    },
    {
      displayName: 'אזור/רחוב',
      propertyName: 'parkingPermitAreasString',
      sortField: 'areaNameAndStreetName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
      textOverflow: true,
    },
    {
      displayName: 'בתוקף מ',
      propertyName: 'startDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'פג תוקף',
      propertyName: 'expirationDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'סוג תו',
      propertyName: 'permitType.name',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
    {
      displayName: 'סטטוס',
      propertyName: 'parkingPermitStatus.name',
      fieldId: 'parkingPermitStatus.statusId',
      canSort: true,
      type: ColumnTypeEnum.Tag,
      sortByServer: false,
    },
    {
      displayName: 'ת. קליטה',
      propertyName: 'requestDate',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: false,
    },
  ];

  public static ParkingPermitTypesColumns: Column[] = [
    {
      displayName: '',
      propertyName: 'isActive',
      canSort: false,
      type: ColumnTypeEnum.Hidden,
      sortByServer: true,
    },
    {
      displayName: 'קוד תו',
      propertyName: 'authorityPermitTypeID',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },

    {
      displayName: 'תיאור ',
      propertyName: 'permitName',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'כמות תווים פעילים ',
      propertyName: 'permitsCount',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'מחיר תו ',
      propertyName: 'cost',
      canSort: true,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
    {
      displayName: 'אזורים  ',
      propertyName: 'areaNames',
      canSort: false,
      type: ColumnTypeEnum.Text,
      sortByServer: true,
    },
  ];
}
