import { ROUTE_PATH } from 'src/app/constants/routerPath';
import { SubModuleNames } from '../enum/moduleEnum';
import { TabAttributes } from '../filters/tabsGroup';
import {
  StepsDescriptionEnum,
  TimelineSettingsEnum,
} from '../enum/timelineSettings.enum';
import { TimelineItem } from './timeline-settings-types';

export class TimelineSettings {
  public static Tabs: TabAttributes[] = [
    {
      disabled: null,
      text: SubModuleNames.TicketTimeline,
      url: `${ROUTE_PATH.Management.Tickets}`,
      name: 'tickets',
    },
    {
      disabled: null,
      text: SubModuleNames.EnforcementTimeline,
      url: `${ROUTE_PATH.Management.Enforcement}`,
      name: 'enforcement',
    },
  ];

  public static TicketsTimelineSteps: TimelineItem[] = [
    {
      text: TimelineSettingsEnum.TicketTimeline,
      imgSrc: 'car.svg',
      isActive: true,
      title: TimelineSettingsEnum.TicketTimeline,
      description: StepsDescriptionEnum.TicketTimeline,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.TicketsWindow}`,
      validateFields: ['DaysToPerformDetailDressing'],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 0,
      isMoveable: false,
      iconId: 0,
      enumName: TimelineSettingsEnum.ReportWindowStep,
    },
    {
      text: TimelineSettingsEnum.TransportOffice,
      imgSrc: 'bus.svg',
      isActive: true,
      title: TimelineSettingsEnum.TransportOffice,
      description: StepsDescriptionEnum.TransportOffice,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.TransportOffice}`,
      validateFields: [],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 1,
      isMoveable: false,
      iconId: 0,
      enumName: TimelineSettingsEnum.MinistryTransportDetailStep,
    },
    {
      text: TimelineSettingsEnum.InformationAuth,
      imgSrc: 'building.svg',
      isActive: true,
      title: TimelineSettingsEnum.InformationAuth,
      description: StepsDescriptionEnum.InformationAuth,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.InformationAuth}`,
      validateFields: [],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 2,
      isMoveable: false,
      iconId: 0,
      enumName: TimelineSettingsEnum.DetailVerificationStep,
    },
    {
      text: TimelineSettingsEnum.EarlyNotice,
      imgSrc: 'danger.svg',
      isActive: true,
      title: TimelineSettingsEnum.EarlyNotice,
      description: StepsDescriptionEnum.EarlyNotice,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.EarlyNotice}`,
      validateFields: ['AdvanceNoticeDaysForPayment'],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 3,
      isMoveable: false,
      iconId: 0,
      enumName: TimelineSettingsEnum.AdvanceNoticeStep,
    },
    {
      text: TimelineSettingsEnum.PaymentNotice,
      imgSrc: 'judgeYellow.svg',
      isActive: true,
      title: TimelineSettingsEnum.PaymentNotice,
      description: StepsDescriptionEnum.PaymentNotice,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.PaymentNotice}`,
      validateFields: [],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 4,
      isMoveable: false,
      iconId: 0,
      enumName: TimelineSettingsEnum.PaymentNoticeStep,
    },
    {
      text: TimelineSettingsEnum.AdminApprovedToEnforce,
      imgSrc: 'judgeOrange.svg',
      isActive: true,
      title: TimelineSettingsEnum.AdminApprovedToEnforce,
      description: StepsDescriptionEnum.AdminApprovedToEnforce,
      lineWidth: '35px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.AdminApprovedToEnforce}`,
      validateFields: [],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 5,
      isMoveable: false,
      iconId: 0,
      enumName: TimelineSettingsEnum.AdminConfirmationStep,
    },
  ];

  public static EnforcementTimelineSteps: TimelineItem[] = [
    {
      text: TimelineSettingsEnum.DetailsConfirmation,
      imgSrc: 'house.svg',
      isActive: true,
      title: TimelineSettingsEnum.DetailsConfirmation,
      description: StepsDescriptionEnum.DetailsConfirmation,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.Enforcement}/${ROUTE_PATH.Management.DetailsConfirmation}`,
      validateFields: [],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 0,
      isMoveable: false,
      iconId: 0,
      enumName: TimelineSettingsEnum.MinistryInteriorDetailStep,
    },
    {
      text: TimelineSettingsEnum.OrderMessage,
      imgSrc: 'judgeYellow.svg',
      isActive: true,
      title: TimelineSettingsEnum.OrderMessage,
      description: StepsDescriptionEnum.OrderMessage,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.Enforcement}/${ROUTE_PATH.Management.OrderMessage}`,
      validateFields: ['DemandNoticeDaysForPayment'],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 1,
      isMoveable: false,
      iconId: 0,
      enumName: TimelineSettingsEnum.DemandNoticeStep,
    },
    {
      text: TimelineSettingsEnum.FormThree,
      imgSrc: 'judgeOrange.svg',
      isActive: true,
      title: TimelineSettingsEnum.FormThree,
      description: StepsDescriptionEnum.FormThree,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.Enforcement}/${ROUTE_PATH.Management.FormThree}`,
      validateFields: ['Form3DaysForPayment'],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 2,
      isMoveable: false,
      iconId: 0,
      enumName: TimelineSettingsEnum.FormThreeStep,
    },
    {
      text: TimelineSettingsEnum.DebtReminder,
      imgSrc: 'yellow-danger.svg',
      isActive: true,
      title: TimelineSettingsEnum.DebtReminder,
      description: StepsDescriptionEnum.DebtReminder,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.Enforcement}/${ROUTE_PATH.Management.DebtReminder}`,
      validateFields: ['DebtReminderDaysForPayment'],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 3,
      isMoveable: false,
      iconId: 0,
      enumName: TimelineSettingsEnum.DebtReminderStep,
    },
    {
      text: TimelineSettingsEnum.BankForeclosure,
      imgSrc: 'bank.svg',
      isActive: true,
      title: TimelineSettingsEnum.BankForeclosure,
      description: StepsDescriptionEnum.BankForeclosure,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.Enforcement}/${ROUTE_PATH.Management.BankForeclosure}`,
      validateFields: [
        'BankNumbersForFirstPhase',
        'BankNumbersForSecondPhase',
        'BankNumbersForThirdPhase',
      ],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 4,
      isMoveable: true,
      iconId: 0,
      enumName: TimelineSettingsEnum.BankForeclosureStep,
    },
    {
      text: TimelineSettingsEnum.TaltalinForeclosureSignUp,
      imgSrc: 'glass.svg',
      isActive: true,
      title: TimelineSettingsEnum.TaltalinForeclosureSignUp,
      description: StepsDescriptionEnum.TaltalinForeclosureSignUp,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.Enforcement}/${ROUTE_PATH.Management.TaltalinForeclosureSignUp}`,
      validateFields: ['RegisteredPropertyDaysForPayment'],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 5,
      isMoveable: true,
      iconId: 0,
      enumName: TimelineSettingsEnum.RegisteredPropertyForeclosureStep,
    },
    {
      text: TimelineSettingsEnum.TaltalinForeclosureOnGoing,
      imgSrc: 'paper-box.svg',
      isActive: true,
      title: TimelineSettingsEnum.TaltalinForeclosureOnGoing,
      description: StepsDescriptionEnum.TaltalinForeclosureOnGoing,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.Enforcement}/${ROUTE_PATH.Management.TaltalinForeclosureOnGoing}`,
      validateFields: [],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 6,
      isMoveable: true,
      iconId: 0,
      enumName: TimelineSettingsEnum.ActualPropertyForeclosureStep,
    },
    {
      text: TimelineSettingsEnum.VehicleForeclosureSignUp,
      imgSrc: 'white-book.svg',
      isActive: true,
      title: TimelineSettingsEnum.VehicleForeclosureSignUp,
      description: StepsDescriptionEnum.VehicleForeclosureSignUp,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.Enforcement}/${ROUTE_PATH.Management.VehicleForeclosureSignUp}`,
      validateFields: [],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 7,
      isMoveable: true,
      iconId: 0,
      enumName: TimelineSettingsEnum.RegisteredCarForeclosureStep,
    },
    {
      text: TimelineSettingsEnum.VehicleForeclosureOnGoing,
      imgSrc: 'blue-car.svg',
      isActive: true,
      title: TimelineSettingsEnum.VehicleForeclosureOnGoing,
      description: StepsDescriptionEnum.VehicleForeclosureOnGoing,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.Enforcement}/${ROUTE_PATH.Management.VehicleForeclosureOnGoing}`,
      validateFields: [],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 8,
      isMoveable: true,
      iconId: 0,
      enumName: TimelineSettingsEnum.ActualCarForeclosureStep,
    },
    {
      text: TimelineSettingsEnum.ThirdSideForeclosure,
      imgSrc: 'yellow-paper.svg',
      isActive: true,
      title: TimelineSettingsEnum.ThirdSideForeclosure,
      description: StepsDescriptionEnum.ThirdSideForeclosure,
      lineWidth: '240px',
      path: `${ROUTE_PATH.Management.Home}/${ROUTE_PATH.Management.TimelineSettings}/${ROUTE_PATH.Management.Enforcement}/${ROUTE_PATH.Management.ThirdSideForeclosure}`,
      validateFields: [],
      errors: 0,
      isUpdated: false,
      updatedCount: 0,
      seen: false,
      order: 9,
      isMoveable: true,
      iconId: 0,
      enumName: TimelineSettingsEnum.ThirdPartyForeclosureStep,
    },
  ];
}
