import { FormsServerResponse } from './authority-form.menu';

export const DEFAULT_FORMS: FormsServerResponse = {
  //admin
  '1': [
    { formName: 'הגשת בקשה לביטול', formKey: 'general-ticket-appeal-request' },
    {
      formName: 'הגשת בקשה להסבה',
      formKey: 'general-ticket-identification-request',
    },
    {
      formName: 'הגשת בקשה להישפט',
      formKey: 'general-ticket-request-to-be-tried',
    },
  ],
  //parking
  '2': [
    { formName: 'הגשת בקשה לביטול', formKey: 'parking-ticket-appeal-request' },
    {
      formName: 'הגשת בקשה להסבה',
      formKey: 'parking-ticket-identification-request',
    },
    {
      formName: 'הגשת בקשה להישפט',
      formKey: 'parking-ticket-request-to-be-tried',
    },
    { formName: 'הגשת בקשה לתו חניה', formKey: 'issuing-parking-permit' },
    { formName: 'ועדת תמרורים', formKey: 'traffic-sign-committee' },
    { formName: 'מודול רכב נטוש' },
    {
      formName: 'בקשה לחידוש תו חניה',
      formKey: 'parking-permit-expiration-check',
    },
  ],
  //general
  '3': [
    {
      formName: 'הגשת בקשה לביטול',
      formKey: 'general-ticket-appeal-request-1',
    }, //FIXME -  need to update key by the portal
    { formName: 'הגשת בקשה להסבה', formKey: 'general-ticket-appeal-request-2' },
    {
      formName: 'הגשת בקשה להישפט',
      formKey: 'general-ticket-appeal-request-3',
    },
  ],
};

export const DEFAULT_FIELDS: any = [
  {
    id: '',
    name: 'ID',
    displayName: 'ת.ז',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 1,
  },
  {
    id: '',
    name: 'FirstName',
    displayName: 'שם פרטי',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 2,
  },
  {
    id: '',
    name: 'LastName',
    displayName: 'שם משפחה',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 3,
  },
  {
    id: '',
    name: 'Birthday',
    displayName: 'תאריך לידה',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 4,
  },
  {
    id: '',
    name: 'Gender',
    displayName: 'מין',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 5,
  },
  {
    id: '',
    name: 'City',
    displayName: 'עיר',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 6,
  },
  {
    id: '',
    name: 'Street',
    displayName: 'רחוב',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 7,
  },
  {
    id: '',
    name: 'House',
    displayName: 'בית',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 8,
  },
  {
    id: '',
    name: 'Apartment',
    displayName: 'דירה',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 9,
  },
  {
    id: '',
    name: 'Entrance',
    displayName: 'כניסה',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 10,
  },
  {
    id: '',
    name: 'PoBox',
    displayName: 'תא דואר',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 11,
  },
  {
    id: '',
    name: 'ZipCode',
    displayName: 'מיקוד',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 12,
  },
  {
    id: '',
    name: 'CellPhone',
    displayName: 'טלפון נייד',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 13,
  },
  {
    id: '',
    name: 'Phone',
    displayName: 'טלפון בית',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 14,
  },
  {
    id: '',
    name: 'Email',
    displayName: 'כתובת מייל',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 15,
  },
  {
    id: '',
    name: 'LicenseNo',
    displayName: 'מספר רישוי',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 16,
  },
  {
    id: '',
    name: 'CarType',
    displayName: 'סוג רכב',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 17,
  },
  {
    id: '',
    name: 'CarColor',
    displayName: 'צבע רכב',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 18,
  },
  {
    id: '',
    name: 'CarModel',
    displayName: 'תוצרת רכב',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 19,
  },
  {
    id: '',
    name: 'FreeText',
    displayName: 'מלל חופשי',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 20,
  },
  { type: 'title', fieldNameValue: ' סריקות', displayOrder: 20.5 },
  {
    id: '',
    name: 'ScanID',
    displayName: 'צילום ת.ז / רשיון נהיגה',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 21,
  },
  {
    id: '',
    name: 'ScanLicense',
    displayName: 'צילום רשיון רכב',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 22,
  },
  {
    id: '',
    name: 'RentalContract',
    displayName: 'חוזה שכירות בתוקף',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 23,
  },
  { type: 'title', fieldNameValue: 'רכב חברה ', displayOrder: 23.5 },
  {
    id: '',
    name: 'WorkplaceConfirmation',
    displayName: 'אישור ממקום העבודה',
    type: 'bool',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 24,
  },
  { type: 'title', fieldNameValue: ' בן משפחה ', displayOrder: 24.5 },
  // {
  //   id: '',
  //   name: 'FamilyMember',
  //   displayName: 'בן משפחה',
  //   type: 'bool',
  //   isRequired: false,
  //   fieldNameValue: null,
  //   displayOrder: 25,
  // },
  {
    id: '',
    name: 'Other1',
    displayName: 'אחר 1',
    type: 'string',
    isRequired: false,
    fieldNameValue: 'test',
    displayOrder: 25,
  },
  {
    id: '',
    name: 'Other2',
    displayName: 'אחר 2',
    type: 'string',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 26,
  },
  {
    id: '',
    name: 'Other3',
    displayName: 'אחר 3',
    type: 'string',
    isRequired: false,
    fieldNameValue: null,
    displayOrder: 27,
  },
];
// export const DEFAULT_FIELDS: any = [
//   {
//     id: '',
//     name: 'ID',
//     displayName: 'ת.ז',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 1,
//   },
//   {
//     id: '',
//     name: 'FirstName',
//     displayName: 'שם פרטי',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 2,
//   },
//   {
//     id: '',
//     name: 'LastName',
//     displayName: 'שם משפחה',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 3,
//   },
//   {
//     id: '',
//     name: 'Birthday',
//     displayName: 'תאריך לידה',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 4,
//   },
//   {
//     id: '',
//     name: 'Gender',
//     displayName: 'מין',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 5,
//   },
//   {
//     id: '',
//     name: 'City',
//     displayName: 'עיר',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 6,
//   },
//   {
//     id: '',
//     name: 'Street',
//     displayName: 'רחוב',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 7,
//   },
//   {
//     id: '',
//     name: 'House',
//     displayName: 'בית',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 8,
//   },
//   {
//     id: '',
//     name: 'Apartment',
//     displayName: 'דירה',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 9,
//   },
//   {
//     id: '',
//     name: 'Entrance',
//     displayName: 'כניסה',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 10,
//   },
//   {
//     id: '',
//     name: 'PoBox',
//     displayName: 'תא דואר',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 11,
//   },
//   {
//     id: '',
//     name: 'ZipCode',
//     displayName: 'מיקוד',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 12,
//   },
//   {
//     id: '',
//     name: 'CellPhone',
//     displayName: 'טלפון נייד',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 13,
//   },
//   {
//     id: '',
//     name: 'Phone',
//     displayName: 'טלפון בית',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 14,
//   },
//   {
//     id: '',
//     name: 'Email',
//     displayName: 'כתובת מייל',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 15,
//   },

//   {
//     id: '',
//     name: 'LicenseNo',
//     displayName: 'מספר רישוי',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 16,
//   },
//   {
//     id: '',
//     name: 'CarType',
//     displayName: 'סוג רכב',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 17,
//   },
//   {
//     id: '',
//     name: 'CarColor',
//     displayName: 'צבע רכב',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 18,
//   },
//   {
//     id: '',
//     name: 'CarModel',
//     displayName: 'תוצרת רכב',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 19,
//   },
//   {
//     id: '',
//     name: 'FreeText',
//     displayName: 'מלל חופשי',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 20,
//   },
//   { type: 'title', fieldNameValue: ' סריקות' },
//   {
//     id: '',
//     name: 'RentalContract',
//     displayName: 'חוזה שכירות בתוקף  ',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 24,
//   },
//   {
//     id: '',
//     name: 'ScanID',
//     displayName: 'צילום ת.ז / רשיון נהיגה',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 21,
//   },
//   {
//     id: '',
//     name: 'ScanLicense',
//     displayName: 'צילום רשיון רכב',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 22,
//   },

//   { type: 'title', fieldNameValue: 'רכב חברה ' },

//   {
//     id: '',
//     name: 'WorkplaceConfirmation',
//     displayName: 'אישור ממקום העבודה',
//     type: 'bool',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 25,
//   },
//   { type: 'title', fieldNameValue: ' בן משפחה ' },
//   // {
//   //   id: '',
//   //   name: 'FamilyMember',
//   //   displayName: 'בן משפחה',
//   //   type: 'bool',
//   //   isRequired: false,
//   //   fieldNameValue: null,
//   //   displayOrder: 26,
//   // },
//   {
//     id: '',
//     name: 'Other1',
//     displayName: 'אחר 1',
//     type: 'string',
//     isRequired: false,
//     fieldNameValue: 'test',
//     displayOrder: 27,
//   },
//   {
//     id: '',
//     name: 'Other2',
//     displayName: 'אחר 2',
//     type: 'string',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 28,
//   },
//   {
//     id: '',
//     name: 'Other3',
//     displayName: 'אחר 3',
//     type: 'string',
//     isRequired: false,
//     fieldNameValue: null,
//     displayOrder: 29,
//   },
// ];
